inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - '**/Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/

# Offense count: 20
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
# AllowedMethods: refine
Metrics/BlockLength:
  Exclude:
    - 'spec/station02/movies_controller_spec.rb'
    - 'spec/station03/movies_controller_spec.rb'
    - 'spec/station04/movies_controller_spec.rb'
    - 'spec/station06/movies_controller_spec.rb'
    - 'spec/station09/movies_controller_spec.rb'
    - 'spec/station09/schedules_controller_spec.rb'
    - 'spec/station10/movies_controller_spec.rb'
    - 'spec/station10/reservations_controller_spec.rb'
    - 'spec/station11/movies_controller_spec.rb'
    - 'spec/station12/reservations_controller_spec.rb'
    - 'spec/station14/users_request_spec.rb'
    - 'db/schema.rb'

# Offense count: 1
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/CyclomaticComplexity:
  Exclude:
    - 'bin/bundle'

# メソッドの行数。一部自動生成コードも含まれる。そこまで複雑でないので無視
# Offense count: 5
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Exclude:
    - 'bin/bundle'

# Offense count: 2
# Configuration parameters: AllowedMethods, AllowedPatterns.
Metrics/PerceivedComplexity:
  Exclude:
    - 'bin/bundle'

# 自動生成なので無視する
# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

# 自動生成なので除外
# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: InverseMethods, InverseBlocks.
Style/InverseMethods:
  Exclude:
    - 'bin/yarn'

# 自動生成なので除外
# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: SafeForConstants.
Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

# rpsecなので除外
# Offense count: 2
# This cop supports unsafe autocorrection (--autocorrect-all).
Style/RedundantInterpolation:
  Exclude:
    - 'spec/station07/sheets_controller_spec.rb'

# 自動生成なので気にしない
# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: RequireEnglish.
# SupportedStyles: use_perl_names, use_english_names, use_builtin_english_names
Style/SpecialGlobalVars:
  Exclude:
    - 'bin/bundle'

# 自動生成なので気にしない
# Offense count: 1
# This cop supports unsafe autocorrection (--autocorrect-all).
# Configuration parameters: AllowMethodsWithArguments, AllowedMethods, AllowedPatterns, AllowComments.
# AllowedMethods: define_method
Style/SymbolProc:
  Exclude:
    - 'db/migrate/20240509051631_create_screens.rb'

# Offense count: 16
# This cop supports safe autocorrection (--autocorrect).
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, AllowedPatterns.
# URISchemes: http, https
Layout/LineLength:
  Exclude:
    - 'spec/station02/movies_controller_spec.rb'
    - 'spec/station03/movies_controller_spec.rb'
    - 'spec/station04/movies_controller_spec.rb'
    - 'spec/station06/movies_controller_spec.rb'
    - 'spec/station09/movies_controller_spec.rb'
    - 'spec/station09/schedules_controller_spec.rb'
    - 'spec/station10/movies_controller_spec.rb'
    - 'spec/station10/reservations_controller_spec.rb'
    - 'spec/station11/movies_controller_spec.rb'
    - 'spec/station12/reservations_controller_spec.rb'
    - 'spec/station14/users_request_spec.rb'
    - 'db/schema.rb'
    - 'bin/bundle'
    - 'config/initializers/devise.rb'