inherit_from: .rubocop_todo.yml
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'lib/**/*'
    - '**/Gemfile'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'spec/**/*'

Metrics/AbcSize:
  Max: 35